In [3]:
import pandas as pd

In [6]:
import os

os.listdir()

['.config', 'sample_data']

In [7]:
import pandas as pd

df = pd.read_excel("dataset_cleaned.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_cleaned.xlsx'

In [8]:
import os

print(os.listdir())

['.config', 'sample_data']

In [10]:
import os
print(os.listdir())

['.config', 'dataset_cleaned.xlsx.csv', 'sample_data']

In [11]:
import os
print(os.listdir())

['.config', 'dataset_cleaned.xlsx.csv', 'sample_data']

In [13]:
import os
print(os.listdir())

['.config', 'dataset_cleaned.xlsx.csv', 'sample_data']

In [14]:
import pandas as pd

df = pd.read_csv("dataset_cleaned.xlsx.csv")

In [15]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,? 5.55
1,2,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-? 5.49
2,3,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,? 4.27
3,4,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-? 64.77
4,5,US-2023-141817,01-05-2023,01-12-2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,? 4.88

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10224 non-null  int64
 1   Order ID        10224 non-null  object
 2   Order Date      10224 non-null  object
 3   Ship Date       10224 non-null  object
 4   Ship Mode       10224 non-null  object
 5   Customer ID     10224 non-null  object
 6   Customer Name   10209 non-null  object
 7   Segment         10224 non-null  object
 8   Country/Region  10224 non-null  object
 9   City            10209 non-null  object
 10  State/Province  10224 non-null  object
 11  Postal Code     10224 non-null  object
 12  Region          10209 non-null  object
 13  Product ID      10224 non-null  object
 14  Category        10209 non-null  object
 15  Sub-Category    10224 non-null  object
 16  Product Name    10224 non-null  object
 17  Sales           10209 non-null  float64
 18  Quantity        10224 non-null  int64
 19  Discount        10224 non-null  float64
 20  Profit          10209 non-null  object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.6+ MB

In [17]:
df.describe()

             Row ID         Sales      Quantity      Discount
count  10224.000000  10209.000000  10224.000000  10224.000000
mean    5095.998533    228.023817      3.790395      0.155300
std     2942.263152    619.469003      2.227671      0.206089
min        1.000000      0.444000      1.000000      0.000000
25%     2547.750000     17.150000      2.000000      0.000000
50%     5094.500000     53.880000      3.000000      0.200000
75%     7643.250000    209.300000      5.000000      0.200000
max    10194.000000  22638.480000     14.000000      0.800000

In [18]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name     15
Segment            0
Country/Region     0
City              15
State/Province     0
Postal Code        0
Region            15
Product ID         0
Category          15
Sub-Category       0
Product Name       0
Sales             15
Quantity           0
Discount           0
Profit            15
dtype: int64

In [19]:
print("Shape:", df.shape)

Shape: (10224, 21)

In [20]:
print("Memory Usage:")
print(df.memory_usage(deep=True))
print("Total Memory:", df.memory_usage(deep=True).sum(), "bytes")

Memory Usage:
Index                132
Row ID             81792
Order ID          644112
Order Date        599287
Ship Date         599221
Ship Mode         632213
Customer ID       582768
Customer Name     634255
Segment           591358
Country/Region    632488
City              595766
State/Province    587932
Postal Code       551246
Region            550183
Product ID        654336
Category          631286
Sub-Category      574560
Product Name      885941
Sales              81792
Quantity           81792
Discount           81792
Profit            571167
dtype: int64
Total Memory: 10845419 bytes

In [21]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01-03-2023,01-07-2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,? 5.55
1,2,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-? 5.49
2,3,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,? 4.27
3,4,US-2023-112326,01-04-2023,01-08-2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-? 64.77
4,5,US-2023-141817,01-05-2023,01-12-2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,? 4.88

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10224 entries, 0 to 10223
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10224 non-null  int64
 1   Order ID        10224 non-null  object
 2   Order Date      10224 non-null  object
 3   Ship Date       10224 non-null  object
 4   Ship Mode       10224 non-null  object
 5   Customer ID     10224 non-null  object
 6   Customer Name   10209 non-null  object
 7   Segment         10224 non-null  object
 8   Country/Region  10224 non-null  object
 9   City            10209 non-null  object
 10  State/Province  10224 non-null  object
 11  Postal Code     10224 non-null  object
 12  Region          10209 non-null  object
 13  Product ID      10224 non-null  object
 14  Category        10209 non-null  object
 15  Sub-Category    10224 non-null  object
 16  Product Name    10224 non-null  object
 17  Sales           10209 non-null  float64
 18  Quantity        10224 non-null  int64
 19  Discount        10224 non-null  float64
 20  Profit          10209 non-null  object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.6+ MB

In [23]:
df.describe()

             Row ID         Sales      Quantity      Discount
count  10224.000000  10209.000000  10224.000000  10224.000000
mean    5095.998533    228.023817      3.790395      0.155300
std     2942.263152    619.469003      2.227671      0.206089
min        1.000000      0.444000      1.000000      0.000000
25%     2547.750000     17.150000      2.000000      0.000000
50%     5094.500000     53.880000      3.000000      0.200000
75%     7643.250000    209.300000      5.000000      0.200000
max    10194.000000  22638.480000     14.000000      0.800000

In [24]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name     15
Segment            0
Country/Region     0
City              15
State/Province     0
Postal Code        0
Region            15
Product ID         0
Category          15
Sub-Category       0
Product Name       0
Sales             15
Quantity           0
Discount           0
Profit            15
dtype: int64

In [25]:
print("Shape of Dataset:", df.shape)

Shape of Dataset: (10224, 21)

In [26]:
print("Memory Usage (bytes):")
print(df.memory_usage(deep=True))
print("Total Memory Used:", df.memory_usage(deep=True).sum(), "bytes")

Memory Usage (bytes):
Index                132
Row ID             81792
Order ID          644112
Order Date        599287
Ship Date         599221
Ship Mode         632213
Customer ID       582768
Customer Name     634255
Segment           591358
Country/Region    632488
City              595766
State/Province    587932
Postal Code       551246
Region            550183
Product ID        654336
Category          631286
Sub-Category      574560
Product Name      885941
Sales              81792
Quantity           81792
Discount           81792
Profit            571167
dtype: int64
Total Memory Used: 10845419 bytes

In [27]:
with open("data_info.txt", "w") as f:
    f.write("=== DATASET INFORMATION ===\n\n")

    df.info(buf=f)

    f.write("\n\n=== DATASET SHAPE ===\n")
    f.write(str(df.shape))

    f.write("\n\n=== MISSING VALUES ===\n")
    f.write(str(df.isnull().sum()))

    f.write("\n\n=== MEMORY USAGE ===\n")
    f.write(str(df.memory_usage(deep=True)))
    f.write("\n\nTotal Memory Used: " + str(df.memory_usage(deep=True).sum()) + " bytes")

In [28]:
from google.colab import files
files.download("data_info.txt")